config/routes.rb
Rails.application.routes.draw do
  resources :line_items
  resources :carts
  resources :instruments
  devise_for :users, controllers: {
    registrations: 'registrations'
  }
  root "instruments#index"
end

app/models/cart.rb
class Cart < ApplicationRecord
    has_many :line_items, dependent: :destroy

    def add_instrument(instrument)
        current_item = line_items.find_by(instrument_id: instrument.id)
        
        if current_item
            current_item.increment(:quantity)
        else
            current_item = line_items.build(instrument_id: instrument.id)
        end

        current_item
    end

    def total_price
        line_items.to_a.sum { |item| item.total_price }
    end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  rescue_from ActiveRecord::RecordNotFound, with: :invalid_cart
  before_action :set_cart, only: %i[ show edit update destroy ]

  # GET /carts or /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1 or /carts/1.json
  def show
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts or /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to cart_url(@cart), notice: "Cart was successfully created." }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1 or /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to cart_url(@cart), notice: "Cart was successfully updated." }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1 or /carts/1.json
  def destroy
    @cart.destroy if @cart.id == session[:cart_id]
    session[:cart_id] = nil

    respond_to do |format|
      format.html { redirect_to root_path, notice: "Cart was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cart_params
      params.fetch(:cart, {})
    end

    def invalid_cart
      logger.error "Attempt to acess invalid cart #{params[:id]}"
      redirect_to root_path, notice: "This cart doesn't exist" 
    end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_cart.html.erb
<div id="<%= dom_id cart %>">
</div>

app/views/carts/_form.html.erb
<%= simple_form_for(@cart) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editando carrinho</h1>

<%= render "form", cart: @cart %>

<br>

<div>
  <%= link_to "Mostrar este carrinho", @cart %> |
  <%= link_to "Voltar para os carrinhos", carts_path %>
</div>

app/views/carts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Carts</h1>

<div id="carts">
  <% @carts.each do |cart| %>
    <%= render cart %>
    <p>
      <%= link_to "Show this cart", cart %>
    </p>
  <% end %>
</div>

<%= link_to "New cart", new_cart_path %>

app/views/carts/new.html.erb
<h1>Novo carrinho</h1>

<%= render "form", cart: @cart %>

<br>

<div>
  <%= link_to "Voltar para os carrinhos", carts_path %>
</div>

app/views/carts/show.html.erb
<div class="continuar-comprando pv1 mt4 has-text-right">
  <%= link_to 'Continuar comprando', instruments_path, class: 'button is-warning' %>
</div>
<hr />
<section class="section">
  <%= render(@cart.line_items) %>

  <div class="columns">
    <div class="column">
      <%= button_to 'Esvaziar carrinho', @cart, method: :delete, data: { confirm: "Você tem certeza? " }, class: "button is-danger" %>
    </div>
    <div class="column total has-text-right">
      <h4 class="title is-4">
        <span class="f5 has-text-grey">Total:</span> <%= number_to_currency(@cart.total_price) %>
      </h4>
    </div>
  </div>
</section>